### ISSUE TITLE
Image upload services 

### ISSUE THREAD

**Issue by jamestang12** [Who-put-that-in-my-drive/Moments#8]
- [x] #11 Implements AWS services for image uploading 
- [x] #10 Create image uploading route/business logic
- [x] #9 Design database schema for image
